Linux-SGX: sgx_framework.c doesn't compile
sgx_framework.c doesn't compile because SGX_INVALID_LICENSE is
renamed to SGX_INVALID_EINITTOKEN.

> sgx_framework.c: In function 'init_enclave':
> sgx_framework.c:348:14: error: 'SGX_INVALID_LICENSE' undeclared (first use in this function); did you mean 'SGX_INVALID_KEYNAME'?
>          case SGX_INVALID_LICENSE:
>          ^~~~~~~~~~~~~~~~~~~
>          SGX_INVALID_KEYNAME