[Pal/Linux-SGX] Remove #include <sys/types.h> from ocall_types.h
There is an incompatibility between system headers, because struct
timeval is defined twice. This problem manifested in such error:

    In file included from ../Pal/src/host/Linux-SGX/linux_types.h:5,
                     from ../Pal/src/host/Linux-SGX/ocall_types.h:9,
                     from ../Pal/src/host/Linux-SGX/generated-offsets.c:8:
    /usr/include/linux/time.h:16:8: error: redefinition of ‘struct timeval’
       16 | struct timeval {
          |        ^~~~~~~
    In file included from /usr/include/x86_64-linux-gnu/sys/select.h:37,
                     from /usr/include/x86_64-linux-gnu/sys/types.h:179,
                     from ../Pal/src/host/Linux-SGX/ocall_types.h:7,
                     from ../Pal/src/host/Linux-SGX/generated-offsets.c:8:
    /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h:8:8: note: originally defined here
        8 | struct timeval
          |        ^~~~~~~

Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>