[Pal/Linux-SGX] Remove #include <sys/types.h> from ocall_types.h
There is an incompatibility between system headers, because struct
timeval is defined twice. This problem manifested in:

    /usr/include/linux/time.h:16:8: error: redefinition of ‘struct timeval’
       16 | struct timeval {
          |        ^~~~~~~

Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>