Pal/Linux-SGX: don't include math.h in sgx_enclave.c
math.h isn't needed in sgx_enclave.c and the header file, math.h,
causes compile error with -mno-sse2 as follows on some environment.
So remove math.h inclusion from sgx_enclave.c.

> [ host/Linux-SGX/sgx_enclave.o ]
> In file included from /usr/include/math.h:426:0,
>                  from sgx_enclave.c:16:
>                  /usr/include/x86_64-linux-gnu/bits/mathinline.h: In
>                  function fabs:
>                  /usr/include/x86_64-linux-gnu/bits/mathinline.h:686:1:
>                  error: SSE register return with SSE disabled
>                   __inline_mathcodeNP_ (double, fabs, __x, return
>                   __builtin_fabs (__x))

Signed-off-by: Isaku Yamahata <isaku.yamahata@gmail.com>