[LibOS,Pal] regression: Clean .pytest_cache
This is apparently needed in Ubuntu 20.04:

    ================================================================================
                    ERROR: Source tree is not unchanged after clean:
    --------------------------------------------------------------------------------
    Only in /tmp/graphene-debug-20.04.clean-check.test/LibOS/shim/test/regression: .pytest_cache
    Only in /tmp/graphene-debug-20.04.clean-check.test/Pal/regression: .pytest_cache
    ================================================================================

Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>