Examples: Upgrade to redis 6.0.5 to avoid linker issues
Using redis 6.0.5 on more recent distros (Fedora 32) avoids linker
issues like the following ones:

    LINK redis-server
/usr/bin/ld: server.o:/home/stefanb/pef-dev/graphene/Examples/redis/src/src/sds.h:37: multiple definition of `SDS_NOINIT'; quicklist.o:/home/stefanb/pef-dev/graphene/Examples/redis/src/src/sds.h:37: first defined here
/usr/bin/ld: sds.o:/home/stefanb/pef-dev/graphene/Examples/redis/src/src/sds.h:37: multiple definition of `SDS_NOINIT'; quicklist.o:/home/stefanb/pef-dev/graphene/Examples/redis/src/src/sds.h:37: first defined here
[...]