[Pal/regression] Hex.c: fix linkage with -O0
__abort() and warn() is not exported by PAL. So define them in Hex.c
to workaround linkage issue as follows.

> /tmp/ccWEEXwg.o: In function `__bytes2hexstr':
> /graphene/Pal/regression/../include/lib/hex.h:41: undefined reference to `warn'
> /graphene/Pal/regression/../include/lib/hex.h:41: undefined reference to `__abort'
> /graphene/Pal/regression/../include/lib/hex.h:41: undefined reference to `warn'
> /graphene/Pal/regression/../include/lib/hex.h:41: undefined reference to `__abort'
> collect2: error: ld returned 1 exit status
> Makefile:100: recipe for target 'Hex' failed