[Examples] Upgrade to Redis 6.0.5 to avoid linker issues
Using Redis 6.0.5 on more recent distros (Fedora 32) avoids linker
issues like the following ones:

  /usr/bin/ld: server.o:sds.h:37: multiple definition of `SDS_NOINIT';
               quicklist.o:sds.h:37: first defined here