[CI] Use C.UTF-8 locale
On python < 3.7 this fixes click safeguard:

    RuntimeError: Click will abort further execution because Python 3
    was configured to use ASCII as encoding for the environment. Consult
    http://click.pocoo.org/python3/ for mitigation steps.

And anyway, unicode-aware locale is a good idea anyway.

Signed-off-by: Wojtek Porczyk <woju@invisiblethingslab.com>